### ISSUE TITLE
Map centering doesn't work

### ISSUE THREAD

**Issue by bertearazvan** [Anabolique89/MuralFinderReact#25]
@Anabolique89 Uite aici un issue pentru problema. Hai sa continuam aici

**Comment by Anabolique89** [comment]
Thanks! 
Eu nici nu am Viewport, nu stiu unde sa-l pun ^^

**Comment by bertearazvan** [comment]
```
// default viewport
const INITIAL_CAMERA = {
    center: {lat: 40.7, lng: -74}, // defaultcenter
    zoom: 12
  }; 

  // State holding the map props
const [cameraProps, setCameraProps] = useState<MapCameraProps>(INITIAL_CAMERA);

// When handleCameraChange, it will update the viewport
  const handleCameraChange = useCallback((ev: MapCameraChangedEvent) =>
    setCameraProps(ev.detail)
  ), []);

<Map
    style={style}
    defaultZoom={10}
    zoom={9}
    center={mapCenter}
    defaultCenter={mapCenter}  // Changed from {{ mapCenter }}
    gestureHandling={'cooperative'}
    zoomControl={true}
    options={mapOptions}
    scrollwheel={true}
    streetViewControl={true}
    onCameraChanged={handleCameraChange}
></Map>
```

**Comment by bertearazvan** [comment]
nu stiu sigur ce contine `MapCameraChangedEvent` insa pare ca contine Map props.

Incearca sa aplici conceptul de aici cu "Controlled map": https://visgl.github.io/react-google-maps/docs/api-reference/components/map#controlled-and-uncontrolled-props

**Comment by bertearazvan** [comment]
iar apoi tu poti sa faci update the state-ul "cameraProps" cu un nou center, but having `onCameraChanged` will update your camera also on drag.

**Comment by Anabolique89** [comment]
Am adaugat in format jsx, am scos centrul si am pastrat defaultCenter, am scos Zoom si am pastrat defaultZoom, problema e ca, de fiecare data cand fac asta nu mai merge Search-ul adreselor. 
I need to be able to let the user search and view a location, so when an adress is typed in, the map goes to that place by itself, like Google map lol :))))). So now it's draggable but the search don't work anymore. :(((( 

Maybe you can open my code in a VS code, npm install and have a look at the stupid map.jsx :)))))) 

I've added that code in here: 

import React, { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Map, Marker, InfoWindow, APIProvider
} from '@vis.gl/react-google-maps';
import { DirectionsRenderer, LoadScript, Autocomplete } from '@react-google-maps/api';
import WallService from '../services/WallService';
import Footer from '../components/Footer';
import styles from '../style';

const Maps = ({ locations, defaultCenter, center, style }) => {
  const navigate = useNavigate();

  const [selectedMarker, setSelectedMarker] = useState(null);
  const [walls, setWalls] = useState([]);
  const [title, setTitle] = useState('');
  const [image, setImage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [mapCenter, setMapCenter] = useState(defaultCenter);
  const [directions, setDirections] = useState(null);
  const [userLocation, setUserLocation] = useState(null);
  const [autocomplete, setAutocomplete] = useState(null);
  const [searchMarker, setSearchMarker] = useState(null);

  const apiKey = "KEY"
  // Default locations if none are provided
  locations = locations || [
    { lat: 37.7749, lng: -122.4194, name: 'Location 1' },
    { lat: 37.7859, lng: -122.4364, name: 'Location 2' },
    { lat: 37.7969, lng: -122.4574, name: 'Location 3' }
  ];
  defaultCenter = defaultCenter || { lat: 37.7749, lng: -122.4194 };
  center = center || defaultCenter;
  style = style || {
    width: '100%',
    height: '100vh',
    border: '2px solid #c2c',
    borderRadius: '8px',
    overflow: 'hidden',
    position: 'relative'
  };

  // Example default bonds for each location
  const defaultBonds = [
    { locationId: 1, connections: ['Location 2', 'Location 3'], additionalInfo: 'This is the main hub.' },
    { locationId: 2, connections: ['Location 1'], additionalInfo: 'Secondary location with a mural.' },
    { locationId: 3, connections: ['Location 1'], additionalInfo: 'A scenic spot with a mural.' }
  ];

  const mapOptions = {
    styles: [
      {
        featureType: 'road',
        elementType: 'geometry',
        stylers: [
          { color: '#4B1EEE' }, // Change road color
          { weight: 1 } // Change road weight
        ]
      },
      {
        featureType: 'road',
        elementType: 'labels.text.fill',
        stylers: [
          { color: '#000000' } // Change road label text color
        ]
      },
      {
        featureType: 'road',
        elementType: 'labels.text.stroke',
        stylers: [
          { color: '#ffffff' } // Change road label text stroke color
        ]
      },
      {
        featureType: 'water',
        elementType: 'geometry',
        stylers: [
          { color: '#27399E' } // Change water color
        ]
      },
      {
        featureType: 'water',
        elementType: 'labels.text.fill',
        stylers: [
          { color: '#ffffff' } // Change water label text color
        ]
      },
      {
        featureType: 'landscape',
        elementType: 'geometry',
        stylers: [
          { color: '#EADAD2' } // Change landscape color
        ]
      },
      {
        featureType: 'poi',
        elementType: 'geometry',
        stylers: [
          { color: '#4660D4' } // Change POI (points of interest) color
        ]
      },
      {
        featureType: 'poi',
        elementType: 'labels.text.fill',
        stylers: [
          { color: '#5C6E94' } // Change POI label text color
        ]
      },
      {
        featureType: 'transit',
        elementType: 'geometry',
        stylers: [
          { color: '#70B4C9' } // Change transit color
        ]
      },
      {
        featureType: 'transit',
        elementType: 'labels.text.fill',
        stylers: [
          { color: '#000000' } // Change transit label text color
        ]
      },
      {
        featureType: 'administrative',
        elementType: 'geometry',
        stylers: [
          { color: '#1C1258' } // Change administrative area color
        ]
      },
      {
        featureType: 'administrative',
        elementType: 'labels.text.fill',
        stylers: [
          { color: '#737373' } // Change administrative label text color
        ]
      }
    ]
  };

  useEffect(() => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          const currentLocation = {
            lat: position.coords.latitude,
            lng: position.coords.longitude,
          };
          setUserLocation(currentLocation);
          setMapCenter(currentLocation);
        },
        (error) => console.error('Error getting user location:', error)
      );
    } else {
      console.error('Geolocation is not supported by this browser.');
    }

    const fetchWallsFromDatabase = async () => {
      try {
        const response = await WallService.getAllWalls();
        if (response.success) {
          console.log(response.data.data);
          setWalls(response.data.data);
        } else {
          console.error('Error fetching walls:', response.message);
        }
      } catch (error) {
        console.error('Error fetching walls:', error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchWallsFromDatabase();
  }, []);

  const handleMarkerClick = (index) => {
    setSelectedMarker(index);
    setTitle(walls[index].location_text);
    setImage(`https://api.muralfinder.net/${walls[index].image_path}`);
  };

  const handleDirections = async (destination) => {
    if (!userLocation) {
      alert('Please allow location access to get directions.');
      return;
    }

    const service = new google.maps.DirectionsService();
    service.route(
      {
        origin: userLocation,
        destination: destination,
        travelMode: google.maps.TravelMode.DRIVING,
      },
      (result, status) => {
        if (status === google.maps.DirectionsStatus.OK) {
          setDirections(result);
        } else {
          console.error(`Error fetching directions ${result}`);
        }
      }
    );
  };

  const handlePlaceChanged = () => {
    const place = autocomplete.getPlace();
    if (place && place.geometry) {
      const newCenter = {
        lat: place.geometry.location.lat(),
        lng: place.geometry.location.lng()
      };
      setMapCenter(newCenter);
      setSearchMarker(newCenter); // Set the marker at the searched location
    }
  };

// default viewport
const INITIAL_CAMERA = {
  center: { lat: 40.7, lng: -74 }, // default center
  zoom: 12,
};

// State holding the map props
const [cameraProps, setCameraProps] = useState(INITIAL_CAMERA);


// When handleCameraChange, it will update the viewport
const handleCameraChange = useCallback((ev) => (
  setCameraProps(ev.detail)
), []);

  return (
    <section>
    <LoadScript googleMapsApiKey={apiKey} libraries={['places']}>
      <APIProvider apiKey={apiKey}>
        <Map
            style={style}
            // defaultZoom={10}
            zoom={9}
            center={mapCenter}
            defaultCenter={mapCenter} 
            gestureHandling={'cooperative'}
            zoomControl={true}
            options={mapOptions}
            scrollwheel={true}
            streetViewControl={true}
            onCameraChanged={handleCameraChange}
            // mapId={'bf51a910020fa25a'}
        >
          <Autocomplete
            onLoad={setAutocomplete}
            onPlaceChanged={handlePlaceChanged}
            className=''
          >
            <input
              type="text"
              placeholder="Search location"
              style={{
                boxSizing: 'border-box',
                border: '2px solid white',
                width: '250px',
                height: '40px',
                padding: '0 12px',
                borderRadius: '20px',
                boxShadow: '0 2px 6px rgba(0, 0, 0, 0.5)',
                fontSize: '16px',
                outline: 'none',
                textOverflow: 'ellipses',
                position: 'absolute',
                left: '50%',
                top: '50px',
                zIndex: '10',
                transform: 'translateX(-50%)',
                backgroundColor: 'rgba(255, 255, 255, 0.8)',
                backdropFilter:' blur(30px)',
                color: '#000'
              }}
            />
          </Autocomplete>
          <button
            onClick={() => navigate('/addWall')}
            style={{
              position: 'absolute',
              left: '50%',
              top: '100px',
              zIndex: '10',
              backgroundColor: '#000',
              padding: '5px 10px',
              borderRadius: '20px',
              boxShadow: '0 2px 6px rgba(0, 0, 0, 0.3)',
              cursor: 'pointer',
              transform: 'translateX(-50%)',
              marginTop: '10px',
              color: '#fff'
            }}
          >
            + ADD WALL
          </button>

          {walls.map((wall, index) => (
            <Marker
              key={index}
              position={{ lat: Number(wall.latitude), lng: Number(wall.longitude) }}
              onClick={() => handleMarkerClick(index)}
            />
          ))}

          {searchMarker && (
            <Marker
              position={searchMarker}
            />
          )}

          {selectedMarker !== null && (
            <InfoWindow
            style={{
              backgroundColor: '#3700b3',
              backgroundSize: 'cover',
              borderRadius: '20px',
              color: '#fff',
              display: 'flex',
              width: '250px',
              height: 'auto',
              zIndex: '20',

            }}
              position={{ lat: Number(walls[selectedMarker].latitude), lng: Number(walls[selectedMarker].longitude) }}
              onCloseClick={() => {
                setSelectedMarker(null);
                setTitle('');
                setImage('');
              }}
            >
              <div className='flex justify-between flex-col px-2 py-2 rounded-[20px] md:mr-2 mr-0 my-2 overflow-hidden z-[25]'>
                <h2 className='font-raleway font-semibold xs:text-[18px] text-[16px] text-white w-full p-2'>{title}</h2>
                <img className='object-cover w-full h-40 mb-4 rounded-md' src={image} alt="Wall" />
                <p className='text-white mb-2'>
                  {defaultBonds[selectedMarker] ? defaultBonds[selectedMarker].additionalInfo : ''}
                </p>
                <button
                  onClick={() => handleDirections(walls[selectedMarker])}
                  disabled={!userLocation}
                  style={{
                 fontFamily:'Raleway',
                 fontSize: '16px',
                 fontWeight: '500',
                    borderRadius: '20px',
                    color: '#fff'
                  }}
                >
                  Get Directions
                </button>
              </div>
            </InfoWindow>
          )}

          {directions && (
            <DirectionsRenderer directions={directions} />
          )}
        </Map>
      </APIProvider>
    </LoadScript>
    <div className={`${styles.paddingX} bg-indigo-600 w-full overflow-hidden`}>
                <Footer />
            </div>
    </section>
  );
};

export default Maps;

**Comment by andrew21-mch** [comment]
thanks @bertearazvan 
worked, 

@Anabolique89 if everything is okay we can close this now
